# Generated by Django 5.2.9 on 2026-01-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='poly_count',
            field=models.IntegerField(default=0),
        ),
    ]
