# Generated by Django 5.2.9 on 2026-01-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_alter_asset_author_asset_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_file',
            field=models.FileField(blank=True, null=True, upload_to='asset_files/'),
        ),
        migrations.AddField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='asset_images/'),
        ),
    ]
